<?php
class Controller
{
	protected $vars   = array();
	protected $layout = 'default';
	protected $title  = SITE_NAME;

	public function __construct()
	{
		spl_autoload_register(array($this, 'loadClass')); // Autoloader de classes
	}

    /**
     * Method generated by the spl_autoload_register function, in order to load automatically a model when called
     */
	public function loadClass($class){
		require(ROOT.'model/'.$class.'.php');
    }

	/**
	 * Magic setters and getters
	 */
	public function __set($name, $value)
    {
        $this->vars[$name] = $value;
    }

    public function __get($name)
    {
        if (array_key_exists($name, $this->vars)) {
            return $this->vars[$name];
        }

        $trace = debug_backtrace();
        trigger_error(
            'Propriété non-définie via __get() : ' . $name .
            ' dans ' . $trace[0]['file'] .
            ' à la ligne ' . $trace[0]['line'],
            E_USER_NOTICE);
        return null;
    }

    /**
     * Loads the layout (by default the "default" layout) 
     * @param string $layout Name of the layout's file
     */
	public function loadLayout($layout = null)
	{
		if($layout == null){
			if(file_exists(ROOT.'layout/'.$this->layout.'.php')){
				require_once(ROOT.'layout/'.$this->layout.'.php');
			}else{
				echo 'Le layout ' . ROOT . 'layout/' . $this->layout . '.php n`existe pas.';
			}
		}else{
			if(file_exists(ROOT.'layout/'.$layout.'.php')){
				$this->layout = $layout;
				require_once(ROOT.'layout/'.$layout.'.php');
			}else{
				echo 'Le layout ' . ROOT . 'layout/' . $layout . '.php n`existe pas.';
			}
		}

		$this->fbUser = $fbUser;
		$this->facebook = $facebook;
	}

    /**
     * Renders the view with the end of the layout if needed (in case we use HTML tags). 
     * @param string $fileName Name of the view's file
     */
	public function render($fileName)
	{
		extract($this->vars); // Allow us to use directly var names instead of "$this->varName"
		// We only render the page once facebook is done loading
		if($fbUser['id']){
			// Loading the view file
			if(file_exists(ROOT.'view/'.strtolower(get_class($this)).'/'.$fileName.'.php')){
				require_once(ROOT.'view/'.strtolower(get_class($this)).'/'.$fileName.'.php');
			}else{
				echo 'La vue ' . ROOT . 'view/' . strtolower(get_class($this)) . '/' . $fileName . '.php n\'existe pas.';
			}

			// Loading the end of the layout in order to put the content between <body> and </body> tags.
			if(file_exists(ROOT.'layout/'.$this->layout.'_end.php')){
				require_once(ROOT.'layout/'.$this->layout.'_end.php');
			}
		}
	}
}