<script type="text/javascript">
$(document).ready(function() {
	$('.reponse').click(function() {
		if ($('.reponse').hasClass("response")) {
			alert('vous avez déja répondu a la question');
		}
		else {
			$('.reponse').removeClass('active');
			$(this).addClass('active');
			$('#derniermot').show();
		}
	});
	$('.yes').click(function() {
		$.ajax();
		$('#derniermot').hide();
		$('.reponse').removeClass('active');
		$('.reponse-3').addClass('response');
	});
	$('.no').click(function() {
		$('#derniermot').hide();
	});
});
</script>
<div id="content">
	<h1>Bienvenue sur Super Quiz ESGI</h1>
	<div id="question">
		<div id="derniermot">
			<img src="<?php echo Quizz::getImageUrl('derniermot.png'); ?>" alt="dernier mot" />
			<div class="button yes">OUI</div>
			<div class="button no" >NON</div>
		</div>
		<div class="number">
			Question <span>10</span>/50
		</div>
		<?php $db = new PDO(DB, USER, PASSWORD); ?>
		<div class="qi_question">
			<?php
			/*
			 * GET QUESTION FROM DATABASE
			 */
			$question = Question::getQuestion();
			if(count($question) > 0){
				$questionId = $question['id'];
				echo $question['question'];
			}else{
				echo 'Aucune question n\'a pu être trouvée.';
			}
			?>
		</div>
		<div class="response_question">
			<?php
			/*
			 * GET ANSWERS FROM DATABASE
			 */
			if($questionId){
				$answers = Answer::getAnswers($questionId);
				if(count($answers) > 0){
					$i = 1;
					foreach ($answers as $answer) {
						echo '<div class="reponse reponse-'.$i.'">'.$answer['answer'].'</div>';
						$i++;
					}
				}else{
					echo 'Aucune réponse n\'a pu être trouvée.';
				}
			}
			?>
		</div>
	</div>	
</div>