<?php
/*
 * Controller question (APPLICATION_ROOT/controllers/index/question.php)
 */
global $user_id;
?>
<script type="text/javascript">
jQuery(document).ready(function() {
	var user_id = <?php echo $user_id; ?>;
	if(user_id && user_id != 0){
		jQuery.ajax({
			type: 'POST',
			url: '<?php echo SITE_ROOT; ?>?action=user',
			dataType: 'html',
			data: { user_id: user_id }
		})
		.done(function(response) {
			console.log('Done');
		})
		.fail(function(response) {
			console.log('Fail');
		});
	}

	jQuery('.yes').click(function() {
		// jQuery.ajax({
		// 	type: 'POST',
		// 	url: '<?php echo SITE_ROOT; ?>?action=answer',
		// 	dataType: 'html',
		// 	data: { answer_id: answerId }
		// })
		// .done(function(response) {
		// 	console.log('Done');
		// 	console.log(response);
		// 	if(response.status == 1) {
		// 		console.log('Bonne réponse');
		// 	} else {
		// 		console.log('Mauvaise réponse');
		// 		jQuery('#derniermot').hide();
		// 		jQuery('.reponse').removeClass('active');
		// 		jQuery('.reponse-3').addClass('response');
		// 	}
		// })
		// .fail(function(response) {
		// 	console.log('Fail');
		// });
	});
	jQuery('.no').click(function() {
		jQuery('#derniermot').hide();
	});
});
</script>
<div id="content">
	<h1>Bienvenue sur Super Quiz ESGI</h1>
	<div id="question">
		<div id="derniermot">
			<img src="<?php echo Quizz::getImageUrl('derniermot.png'); ?>" alt="dernier mot" />
			<div class="button yes">OUI</div>
			<div class="button no" >NON</div>
		</div>
		<div class="number">
			Question <span>10</span>/50
		</div>
		<div class="qi_question">
			<?php
			/*
			 * GET QUESTION FROM DATABASE
			 */
			// $question comes from question controller
			if(count($question) > 0){
				echo $question['question'];
			}else{
				echo 'Aucune question n\'a pu être trouvée.';
			}
			?>
		</div>
		<div class="response_question">
			<?php
			/*
			 * GET ANSWERS FROM DATABASE
			 */
			if($questionId){
				// $answers comes from question controller
				if(count($answers) > 0){
					$i = 1;
					foreach ($answers as $answer) {
						echo '<div id="' . $answer['id'] . '" class="reponse reponse-'.$i.'">'.$answer['answer'].'</div>';
						$i++;
					}
				}else{
					echo 'Aucune réponse n\'a pu être trouvée.';
				}
			}
			?>
		</div>
	</div>	
</div>